### ISSUE TITLE
Create Login modal

### ISSUE THREAD

**Issue by O-KenneDevWorks** [CelestialChai/event-planner#3]
### Front End
Create login modal, Login/signup option, Needs to accept username and password, Needs to have cancel and Login buttons

### Back End
Create API to check the database for the user and sign them in, returning a JWT (JSON Web Token) to the users browser.

**Comment by TheOnlyOneOriginalGenius** [comment]
Perfect!!!

**Comment by TheOnlyOneOriginalGenius** [comment]
{
  "name": "event-planner",
  "version": "1.0.0",
  "description": "initial git hub push",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "npm run client:build && npm run server",
    "start:dev": "concurrently \"npm run server:dev\" \"wait-on tcp:3001 && npm run client:dev\"",
    "server": "cd server && npm start",
    "server:dev": "cd server && npm run dev",
    "install": "cd server && npm i && cd ../client && npm i",
    "client:build": "cd client && npm run build",
    "client:dev": "cd client && npm run dev",
    "build": "cd client && npm run build",
    "seed": "cd server && npm run seed",
    "render-build": "npm install && npm run build"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "concurrently": "^9.1.0",
    "nodemon": "^3.1.7",
    "prettier": "^3.3.3",
    "wait-on": "^8.0.1"
  },
  "dependencies": {
    "bcrypt": "^5.1.1",
    "eslint-config-prettier": "^9.1.0",
    "jsonwebtoken": "^9.0.2",
    "sequelize": "^6.37.5",
    "sqlite3": "^5.1.7"
  }
}
